-- Crochet by Alae — admin-only security audit
-- Run this once in Supabase SQL Editor after the main schema.
-- This records admin login attempts and authenticated admin actions only.

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_email text not null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  ip_hint text,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_log_created_at_idx
  on public.admin_audit_log (created_at desc);

alter table public.admin_audit_log enable row level security;

create or replace function public.is_admin_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select lower(coalesce(auth.jwt() ->> 'email', '')) = 'admin.crochetbyalae@gmail.com';
$$;

drop policy if exists "Admin can read admin audit log" on public.admin_audit_log;
create policy "Admin can read admin audit log"
  on public.admin_audit_log
  for select
  to authenticated
  using (public.is_admin_user());

revoke all on public.admin_audit_log from anon;
revoke all on public.admin_audit_log from authenticated;
grant select on public.admin_audit_log to authenticated;

create or replace function public.log_admin_login_attempt(
  attempted_email text,
  was_success boolean,
  metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_email text := lower(trim(coalesce(attempted_email, '')));
begin
  if normalized_email = '' then
    return;
  end if;

  -- A successful event is accepted only from the authenticated admin session.
  if was_success and not public.is_admin_user() then
    return;
  end if;

  -- Keep repeated failures useful without allowing an uncontrolled flood.
  if not was_success and (
    select count(*) from public.admin_audit_log
    where admin_email = normalized_email
      and action = 'login_failure'
      and created_at > now() - interval '15 minutes'
  ) >= 25 then
    return;
  end if;

  insert into public.admin_audit_log (admin_email, action, details)
  values (
    normalized_email,
    case when was_success then 'login_success' else 'login_failure' end,
    coalesce(metadata, '{}'::jsonb)
  );
end;
$$;

revoke all on function public.log_admin_login_attempt(text, boolean, jsonb) from public;
grant execute on function public.log_admin_login_attempt(text, boolean, jsonb) to anon, authenticated;

create or replace function public.log_admin_page_attempt(
  attempted_email text default '[unknown]',
  path_name text default '/admin'
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_email text := lower(trim(coalesce(attempted_email, '[unknown]')));
begin
  if normalized_email = '' then normalized_email := '[unknown]'; end if;
  if (
    select count(*) from public.admin_audit_log
    where admin_email = normalized_email
      and action = 'admin_page_access_denied'
      and created_at > now() - interval '15 minutes'
  ) >= 50 then
    return;
  end if;
  insert into public.admin_audit_log (admin_email, action, details)
  values (normalized_email, 'admin_page_access_denied', jsonb_build_object('path', coalesce(path_name, '/admin')));
end;
$$;

revoke all on function public.log_admin_page_attempt(text, text) from public;
grant execute on function public.log_admin_page_attempt(text, text) to anon, authenticated;

create or replace function public.log_admin_action(
  action_name text,
  metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin_user() or coalesce(trim(action_name), '') = '' then
    return;
  end if;

  insert into public.admin_audit_log (admin_email, action, details)
  values (lower(auth.jwt() ->> 'email'), trim(action_name), coalesce(metadata, '{}'::jsonb));
end;
$$;

revoke all on function public.log_admin_action(text, jsonb) from public;
grant execute on function public.log_admin_action(text, jsonb) to authenticated;
