-- Crochet by Alae — secure admin access requests
-- Apply after supabase_admin_management.sql.
-- Passwords are handled only by Supabase Auth and are never stored in this table,
-- RPC payloads, Edge Function logs, audit records, or admin metadata.

create table if not exists public.admin_access_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  full_name text not null check (char_length(trim(full_name)) between 1 and 120),
  family_name text not null check (char_length(trim(family_name)) between 1 and 120),
  email text not null,
  additional_info text check (additional_info is null or char_length(additional_info) <= 1000),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  reviewed_by text,
  reviewed_at timestamptz,
  review_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.admin_access_requests add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.admin_access_requests add column if not exists additional_info text;
-- Drop the legacy function before dropping the column it references.
drop function if exists public.submit_admin_access_request(text, text, text, text[]);
alter table public.admin_access_requests drop column if exists requested_permissions;

alter table public.admin_access_requests drop constraint if exists admin_access_requests_additional_info_check;
alter table public.admin_access_requests
  add constraint admin_access_requests_additional_info_check
  check (additional_info is null or char_length(additional_info) <= 1000);

create unique index if not exists admin_access_requests_pending_email_idx
  on public.admin_access_requests (lower(email))
  where status = 'pending';

create unique index if not exists admin_access_requests_pending_user_idx
  on public.admin_access_requests (user_id)
  where status = 'pending' and user_id is not null;

create index if not exists admin_access_requests_status_created_idx
  on public.admin_access_requests (status, created_at desc);

create index if not exists admin_access_requests_user_idx
  on public.admin_access_requests (user_id);

alter table public.admin_access_requests enable row level security;

drop policy if exists "Admins with user management can read access requests" on public.admin_access_requests;
create policy "Admins with user management can read access requests"
  on public.admin_access_requests for select to authenticated
  using (public.is_admin_permission_allowed('admin_users.manage'));

revoke all on public.admin_access_requests from anon;
revoke all on public.admin_access_requests from authenticated;
grant select on public.admin_access_requests to authenticated;

create or replace function public.touch_admin_access_requests_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists admin_access_requests_updated_at on public.admin_access_requests;
create trigger admin_access_requests_updated_at
before update on public.admin_access_requests
for each row execute function public.touch_admin_access_requests_updated_at();

-- Registration is created by Supabase Auth first. This trigger derives the
-- identity from NEW.id and NEW.email, so the browser can never choose another
-- user's UUID or email. Passwords remain exclusively inside Supabase Auth.
drop function if exists public.submit_admin_access_request(text, text, text, uuid, text);

create or replace function public.create_admin_access_request_from_auth()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  metadata jsonb := coalesce(new.raw_user_meta_data, '{}'::jsonb);
  applicant_full_name text := trim(coalesce(metadata->>'full_name', ''));
  applicant_family_name text := trim(coalesce(metadata->>'family_name', ''));
  applicant_email text := lower(trim(coalesce(new.email, '')));
  applicant_additional_info text := nullif(trim(coalesce(metadata->>'additional_info', '')), '');
begin
  if coalesce(metadata->>'admin_onboarding', '') <> 'true' then
    return new;
  end if;

  if new.id is null
     or applicant_email !~ '^\S+@\S+\.\S+$'
     or char_length(applicant_full_name) not between 1 and 120
     or char_length(applicant_family_name) not between 1 and 120 then
    return new;
  end if;

  insert into public.admin_access_requests (
    user_id,
    full_name,
    family_name,
    email,
    additional_info
  )
  values (
    new.id,
    applicant_full_name,
    applicant_family_name,
    applicant_email,
    left(applicant_additional_info, 1000)
  )
  on conflict do nothing;

  return new;
end;
$$;

revoke all on function public.create_admin_access_request_from_auth() from public;

drop trigger if exists on_auth_user_created_admin_access_request on auth.users;
create trigger on_auth_user_created_admin_access_request
  after insert on auth.users
  for each row execute function public.create_admin_access_request_from_auth();

-- An authenticated applicant can see only their own request state. It intentionally
-- returns no identity, permissions, or other applicants' data.
create or replace function public.get_my_request_status()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  request_status jsonb;
begin
  if auth.uid() is null then
    return null;
  end if;

  select jsonb_build_object(
    'status', status,
    'review_note', nullif(review_note, '')
  ) into request_status
  from public.admin_access_requests
  where user_id = auth.uid()
  order by created_at desc
  limit 1;

  return request_status;
end;
$$;

revoke all on function public.get_my_request_status() from public;
grant execute on function public.get_my_request_status() to authenticated;

-- Tighten the existing admin list policy: only the configured Super Admin may
-- enumerate current admin identities. Delegated admins may still review requests
-- when they have admin_users.manage, without seeing the admin_users table.
drop policy if exists "Admins with user management can read admin users" on public.admin_users;
drop policy if exists "Only Super Admin can read admin users" on public.admin_users;
create policy "Only Super Admin can read admin users"
  on public.admin_users for select to authenticated
  using (public.is_super_admin_user());
