/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      // "Stitch & Soul" design system — copied 1:1 from the Google Stitch
      // redesign export (stitch_soul/DESIGN.md + each screen's code.html).
      colors: {
        'on-secondary': '#ffffff',
        'surface-container-high': '#eae7e7',
        'on-background': '#1c1b1b',
        'surface-bright': '#fcf9f8',
        'primary-fixed-dim': '#ffb1c5',
        'error-container': '#ffdad6',
        'on-primary-container': '#591e32',
        'tertiary-container': '#a19b8e',
        'on-tertiary-fixed': '#1e1b13',
        surface: '#fcf9f8',
        primary: '#8d495d',
        error: '#ba1a1a',
        'tertiary-fixed-dim': '#cdc6b8',
        'surface-container-low': '#f6f3f2',
        'on-secondary-fixed-variant': '#5f3d46',
        'surface-container-highest': '#e5e2e1',
        'on-tertiary': '#ffffff',
        'outline-variant': '#d7c1c5',
        'on-tertiary-container': '#373329',
        'inverse-surface': '#313030',
        'on-surface-variant': '#524346',
        'surface-variant': '#e5e2e1',
        'on-secondary-fixed': '#2e131b',
        'on-primary-fixed-variant': '#713246',
        'primary-fixed': '#ffd9e1',
        background: '#fcf9f8',
        'on-error': '#ffffff',
        outline: '#847376',
        'surface-tint': '#8d495d',
        'tertiary-fixed': '#e9e2d3',
        'inverse-primary': '#ffb1c5',
        'secondary-container': '#fdced8',
        tertiary: '#635e53',
        'on-primary-fixed': '#3b061b',
        'primary-container': '#d4849a',
        'on-secondary-container': '#79555e',
        'surface-container': '#f0eded',
        'secondary-fixed-dim': '#e9bbc5',
        'on-error-container': '#93000a',
        secondary: '#79545d',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#dcd9d9',
        'on-tertiary-fixed-variant': '#4b463c',
        'inverse-on-surface': '#f3f0ef',
        'secondary-fixed': '#ffd9e0',
        'on-surface': '#1c1b1b',
        // Dark-mode background used directly as an arbitrary value elsewhere: #1A1A1A
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        gutter: '24px',
        'margin-edge': '40px',
        'container-max': '1280px',
        'section-gap': '120px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        'headline-md': ['Quicksand'],
        'headline-lg': ['Quicksand'],
        'label-sm': ['Plus Jakarta Sans'],
        'display-lg': ['Quicksand'],
        'body-lg': ['Plus Jakarta Sans'],
        'body-md': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-lg': ['40px', { lineHeight: '48px', fontWeight: '600' }],
        'label-sm': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
